version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: song-container
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=song
      - POSTGRES_DB=song
